version: "3.6"

services:
  app1:
    build: ./serv lab2 Ktor/
    container_name: back
    volumes:
      - ./serv lab2 Ktor/:/serv lab2 Ktor
    ports:
      - 8080:8080
    expose:
      - 8080
  app2:
    build: ./vuetest/
    container_name: front
    volumes:
      - ./:/vuetest
    ports:
      - 8081:8081
    expose:
      - 8081